name: build

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm i
      env:
        CI: true
    - name: Build server
      run: npm run build-server
      env:
        CI: true
    - name: Build client
      run: npm run build-client
      env:
        CI: true
